pluginPrefix: "<white><bold>Hooks » </bold>"

webhooks:
  authme: ""
  store: ""

##########################################################################
# Language
##########################################################################
lang:
  missingPermissions: "&cYou don't have the required permissions!"