pluginPrefix: "<white><bold>Hooks » </bold>"

webhooks:
  store: ""
  matrix: ""

##########################################################################
# Language
##########################################################################
lang:
  missingPermissions: "&cYou don't have the required permissions!"