name: DiscordLocalHooks
version: ${version}
author: budi1200
main: si.budimir.discordLocalHooks.DiscordLocalHooksMain
api-version: 1.17
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.31
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.0-RC
  - com.squareup.okhttp3:okhttp:4.9.1
commands:
  dlh:
    description: Plugin command
    usage: /dlh

permissions:
  discordlocalhooks.admin:
    description: Admin actions
    default: op